.codeclimate.yml

Renamed file

---

forms/account.py
forms/admission.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission_form.html
views/admission.py

IUFC-155 Formulaire création admission

---

views/admission.py

Skip getting email from user as users created in osis-portal are not registered in osis

retrieve user email from person

---

forms/admission.py

IUFC-155 Restrict EducationGroupYear choices for formation

IUFC-155 Restrict EducationGroupYear choices for formation

---

business/admission.py
fixtures/admission_created_email_templates.json
models/admission.py
tests/business/test_admission.py
tests/models/test_admission.py

IUFC-156 Send email to participant when admission is created

IUFC-156 Send email to participant when admission is created

---

business/admission.py
fixtures/registration_validated_email_templates.json
tests/business/test_admission.py
tests/views/test_admission.py
tests/views/test_registration.py
views/admission.py

WIP car je vais reprendre les tests faits dans l'autre PR (une fois mergée) pour tester celle-ci.

IUFC-321 : Send mail when registration validated

---

static/js/continuing_xls.js
templates/blocks/button/xls.html
templates/fragment/tab_documents.html

to be merge after the one from base on the same ticket number

[Osis 3637] Le spinner ne disparait pas après avoir créer une feuille XLS

---

business/admission.py
tests/business/test_admission.py

Modifications qui seront validées :
modifié :         business/admission.py
modifié :         tests/business/test_admission.py

OSIS-3981 : Fixed test en prévision d'une modification de modèle Person

---

tests/views/test_admission.py

Fixed test suite au changement du modèle Person (Field email not null)
Modifications qui seront validées :
modifié :         tests/views/test_admission.py

OSIS-3981 Fixed test

---

templates/blocks/button/xls.html
templates/fragment/tab_documents.html
views/file.py

This reverts commit 9089339e88d410f526dcc010d318f5fdf07b7f81, reversing
changes made to 5de5c20fc8d2978f71078a911033e9ba8bf56815.

Revert "Merge pull request #418 from uclouvain/OSIS-4023"

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
models/enums/ucl_registration_error_choices.py

Attendre confirmation du message d'erreur générique

IUFC-674 add unknwown error to UCLRegistrationError choice enum

---

models/address.py
models/admission.py
models/file.py
models/person_training.py
models/prospect.py

Add search_fields, list_display, raw_id_fields, list_filter to improve admin pages

Improve admin pages

---

templates/blocks/button/xls.html
templates/fragment/tab_documents.html
views/file.py

! à merger seulement quand osis_common à jour en QA !
This reverts commit ebc02d5e87d175c24543544646555b679794c989, reversing
changes made to 27bc28c5d2bb6c9a09ef665e9dae4bad7d5c6c78.

OSIS-4023 use download class and cookie decorator to trigger spinner

---

business/prospect.py
business/xls/xls_prospect.py
templates/prospects.html
tests/business/test_prospect.py
tests/views/test_prospect.py
views/prospect.py

IUFC-726 Filter prospects list and xls by manager's trainings

---

business/prospect.py
business/xls/xls_prospect.py
templates/prospects.html
tests/business/test_prospect.py
tests/views/test_prospect.py
views/prospect.py

Pull request automatique de hotfix/IUFC-726 vers DEV

[hotfix/IUFC-726 => DEV] Liste prospects trop large

---

models/continuing_education_training.py

Pull request automatique de hotfix/IUFC-735 vers DEV

[hotfix/IUFC-735 => DEV] Continuing education lists unavailable

---

views/admission.py

…r sur une liste au lieu d'une queryset

Release 4.1

---

auth/roles/continuing_education_manager.py
auth/roles/continuing_education_training_manager.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
static/js/archive.js
templates/admissions.html
templates/blocks/button/archive.html
tests/views/test_admission.py
urls.py
views/admission.py

Pull request automatique de technical/IUFC-746 vers DEV

[technical/IUFC-746 => DEV] Ajouter la possibilité de supprimer des brouillons

---

business/registration_queue.py
forms/address.py
tests/business/test_registration_queue.py

Pull request automatique de technical/IUFC-745 vers DEV

[technical/IUFC-745 => DEV] Assurer l_intégrité OSIS/EPC au  niveaux de la longueur des champs

---

business/xls/xls_admission.py
business/xls/xls_archive.py
business/xls/xls_common.py
business/xls/xls_registration.py
tests/business/xls/test_xls_admission.py
tests/business/xls/test_xls_common.py

Pull request automatique de technical/IUFC-747 vers DEV

[technical/IUFC-747 => DEV] Ajouter le champ domaine d_étude dans le fichier xls

---

forms/address.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
static/js/registration_addresses.js

Pull request automatique de technical/IUFC-744 vers DEV

[WIP] [technical/IUFC-744 => DEV] Assurer intégrité code postaux/localité

---

auth/roles/continuing_education_manager.py
auth/roles/continuing_education_training_manager.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/continuing_education/prospects.html
tests/views/test_prospect.py
urls.py
views/prospect.py

Pull request automatique de feature/IUFC-757 vers DEV

[feature/IUFC-757 => DEV] Permettre la suppression des prospects par les gestionnaires

---

forms/admission.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
models/address.py

[To Test] Release

---

forms/admission.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
models/address.py

[To QA] Release
